---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: developer
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: anupam.bhattacharya@in.ibm.com
      space: dev
      application: FundTransferApp-anupamb-1530
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent
